### ISSUE TITLE
Confusion over names and versions in official releases

### ISSUE THREAD

**Issue by FranklinChen** [melsman/mlkit#21]
A submission I made to Homebrew has been put on hold because of confusion over names and versions of mlkit on the "releases" page. Any comments?

https://github.com/Homebrew/homebrew-core/pull/27999#issuecomment-390205541

**Comment by melsman** [comment]
Sorry for the kate reply. Version 4.3.12 is the most recent release of the
sources. The versioned sources are the comprised sources for smltojs,
smlserver, and mlkit, thus, there are sometimes commits to the mlkit part
without the other tools being affected (and the other way around). The
setup is not perfect, but it is the reason for the releases not always
agreeing on the versioning number... You should be ok by just picking the
highest version number.

lør. 26. maj 2018 kl. 17.21 skrev ilovezfs <notifications@github.com>:

**Comment by ilovezfs** [comment]
@melsman OK thanks for confirming that. Can you please remove the explict GitHub release https://github.com/melsman/mlkit/releases/tag/smltojs-4.3.11 so that  https://github.com/melsman/mlkit/releases/latest just becomes a redirect to https://github.com/melsman/mlkit/releases instead of pointing to 4.3.11? Thanks!
